apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: myapp
spec:
  #nodify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: mynode
          image: gcr.io/sit323-23t1-lora-liu-27b6c44/node-web-app:latest
          ports:
          - containerPort: 8080

